name: flutter_pos_sqlite
description: Simple POS app with login/register, menu,cart, and transaction using SQLite.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.0.11 
  intl: ^0.19.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  sqflite_common_ffi_web: ^1.0.1+1
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


